server:
  port: 8086

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.database.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

product:
  service:
    uri: http://35.184.19.183/products/
customer:
  service:
    uri: http://35.184.19.183/customers/
cart:
  service:
    uri: http://35.184.19.183/carts/
inventory:
  service:
    uri: http://35.184.19.183/inventory/
payment:
  service:
    uri: http://35.184.19.183/payments/