server:
  port: 8086

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.database.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
#
#product:
#  service:
#    uri: http://localhost:8088/
#customer:
#  service:
#    uri: http://localhost:8084/
#cart:
#  service:
#    uri: http://localhost:8081/
#inventory:
#  service:
#    uri: http://localhost:8085/