kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: dev
    name: order
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: order
      spec:
        containers:
        - name: order
          image: reactivesw/order:0.0.4
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: server_port
            value: "80"
          - name: spring_datasource_url
            value: jdbc:postgresql://reactivesw-data/orders
          - name: spring_cloud_config_uri
            value: http://reactivesw-config
          - name: cart_service_uri
            value: http://cart/
          - name: customer_service_uri
            value: http://customer-info/
          - name: inventory_service_uri
            value: http://inventory/
          - name: product_service_uri
            value: http://product/
          - name: payment_service_uri
            value: http://payment/
          - name: io_reactivesw_message_google_project_id
            value: reactivesw-project
          - name: io_reactivesw_message_topic_ordercreated_name
            value: reactivesw-dev-order-created
          - name: io_reactivesw_message_topic_ordercreated_version
            value: reactivesw-dev-order-created
          - name: io_reactivesw_message_topic_ordercreated_subscriber
            value: dev-inventory-order-reserved
          - name: io_reactivesw_message_topic_orderpayed_subscriber
            value: dev-payment-order-payed
          - name: jwt_secret
            valueFrom:
              secretKeyRef:
                name: reactivesw-secret
                key: jwt.secret
- kind: Service
  apiVersion: v1
  metadata:
    name: order
    namespace: dev
    labels:
      name: order
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30107
    selector:
      name: order

